2021-02-25 07:02:52,130 DEBUG    [database_managment.py:26] New log file created and 'Database' object referred to utils/database_file.db.
2021-02-25 07:02:52,130 DEBUG    [database_managment.py:28] Checking if utils/database_file.db exists
2021-02-25 07:02:52,130 DEBUG    [database_managment.py:30] utils/database_file.db exists
2021-02-25 07:02:52,130 DEBUG    [database_managment.py:50] Checking if utils/database_file.db exists
2021-02-25 07:02:52,131 DEBUG    [database_managment.py:52] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-25 07:02:52,136 DEBUG    [app.py:29] Initializing Flask app.
2021-02-25 07:02:52,139 DEBUG    [app.py:33] Permanent session lifetime set
2021-02-25 07:02:52,153 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-25 07:02:52,242 INFO     [_internal.py:113]  * Debugger PIN: 548-289-000
2021-02-25 07:02:57,199 ERROR    [app.py:41] A session wasn't found when trying to load the 'home' page. Redirecting to 'login' page.
2021-02-25 07:02:57,200 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:02:57] "[32mGET / HTTP/1.1[0m" 302 -
2021-02-25 07:02:57,222 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:02:57] "[37mGET /login HTTP/1.1[0m" 200 -
2021-02-25 07:02:57,502 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:02:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2021-02-25 07:03:01,905 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:01] "[32mPOST /login HTTP/1.1[0m" 302 -
2021-02-25 07:03:01,922 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:01] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-25 07:03:09,489 DEBUG    [database_managment.py:115] Gathering balances
2021-02-25 07:03:09,500 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:09] "[37mGET /totals HTTP/1.1[0m" 200 -
2021-02-25 07:03:10,559 DEBUG    [app.py:126] Checking for session
2021-02-25 07:03:10,560 DEBUG    [database_managment.py:149] Geting the names in the 'operaciones' table.
2021-02-25 07:03:10,560 DEBUG    [database_managment.py:160] There are no clients yet!
2021-02-25 07:03:10,584 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:10] "[37mGET /operations HTTP/1.1[0m" 200 -
2021-02-25 07:03:12,184 DEBUG    [app.py:64] Checking for session
2021-02-25 07:03:12,184 DEBUG    [app.py:66] Session for patricia found.
2021-02-25 07:03:12,184 DEBUG    [app.py:93] GET request received. Getting the clients and rendering html.
2021-02-25 07:03:12,184 DEBUG    [database_managment.py:149] Geting the names in the 'operaciones' table.
2021-02-25 07:03:12,184 DEBUG    [database_managment.py:160] There are no clients yet!
2021-02-25 07:03:12,194 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:12] "[37mGET /add HTTP/1.1[0m" 200 -
2021-02-25 07:03:21,188 DEBUG    [app.py:64] Checking for session
2021-02-25 07:03:21,189 DEBUG    [app.py:66] Session for patricia found.
2021-02-25 07:03:21,189 DEBUG    [app.py:69] POST request received. Getting the form's data
2021-02-25 07:03:21,189 DEBUG    [app.py:78] Conditions for adding operation matched. Checking the names
2021-02-25 07:03:21,189 DEBUG    [database_managment.py:91] Try to get today's date and add the operation.
2021-02-25 07:03:21,195 DEBUG    [database_managment.py:99] Updating the 'saldos' table.
2021-02-25 07:03:21,202 DEBUG    [app.py:84] Added  Sdgh 's debt for $100.00
2021-02-25 07:03:21,202 DEBUG    [app.py:85] Changing values in strings for showing them.
2021-02-25 07:03:21,211 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:21] "[37mPOST /add HTTP/1.1[0m" 200 -
2021-02-25 07:03:34,877 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:34] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-25 07:03:35,820 DEBUG    [app.py:126] Checking for session
2021-02-25 07:03:35,820 DEBUG    [database_managment.py:149] Geting the names in the 'operaciones' table.
2021-02-25 07:03:35,820 DEBUG    [database_managment.py:153] Clients found. Saving them into a set
2021-02-25 07:03:35,820 DEBUG    [database_managment.py:158] Returning these clients as a list
2021-02-25 07:03:35,822 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:35] "[37mGET /operations HTTP/1.1[0m" 200 -
2021-02-25 07:03:37,182 DEBUG    [app.py:126] Checking for session
2021-02-25 07:03:37,184 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:37] "[32mPOST /operations HTTP/1.1[0m" 302 -
2021-02-25 07:03:37,204 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:37] "[37mGET /show_operations?client=Sdgh HTTP/1.1[0m" 200 -
2021-02-25 07:03:40,582 DEBUG    [app.py:186] Maintenance tab opened. Searching for session.
2021-02-25 07:03:40,591 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:40] "[37mGET /maintenance HTTP/1.1[0m" 200 -
2021-02-25 07:03:43,442 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:43] "[32mGET /logout HTTP/1.1[0m" 302 -
2021-02-25 07:03:43,450 ERROR    [app.py:41] A session wasn't found when trying to load the 'home' page. Redirecting to 'login' page.
2021-02-25 07:03:43,451 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:43] "[32mGET / HTTP/1.1[0m" 302 -
2021-02-25 07:03:43,458 INFO     [_internal.py:113] 127.0.0.1 - - [25/Feb/2021 07:03:43] "[37mGET /login HTTP/1.1[0m" 200 -
