2021-02-07 10:43:53,335 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-07 10:43:53,336 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-07 10:43:53,336 ERROR    [database_managment.py:47] utils/database_file.db wasn't found. Creating a new one...
2021-02-07 10:43:53,337 DEBUG    [database_managment.py:49] utils/database_file.db successfully created.
2021-02-07 10:43:53,337 DEBUG    [database_managment.py:50] Creating the 'operaciones' and 'saldos' tables in utils/database_file.db
2021-02-20 08:47:41,523 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 08:47:41,523 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 08:47:41,523 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 08:58:52,109 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 08:58:52,109 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 08:58:52,110 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 08:59:38,323 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 08:59:38,323 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 08:59:38,323 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:01:33,404 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:01:33,405 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:01:33,405 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:01:33,425 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:01:33,426 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:01:33,615 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:01:33,615 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:01:33,615 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:01:33,632 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:01:33,709 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:02:21,982 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:21,982 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:21,982 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:22,005 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:02:22,006 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:02:22,194 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:22,195 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:22,195 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:22,210 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:02:22,210 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:02:34,285 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/app.py', reloading
2021-02-20 09:02:34,328 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:02:34,530 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:34,530 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:34,530 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:34,550 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:02:34,550 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:02:37,294 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:37,294 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:37,294 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:37,313 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:02:37,314 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:02:37,499 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:37,499 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:37,499 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:37,517 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:02:37,518 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:02:41,542 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/app.py', reloading
2021-02-20 09:02:41,586 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:02:41,785 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:41,786 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:41,786 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:41,803 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:02:41,803 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:02:44,090 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:44,090 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:44,090 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:44,108 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:02:44,109 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:02:44,296 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:02:44,296 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:02:44,296 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:02:44,314 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:02:44,315 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:03:11,608 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:03:11] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:03:26,276 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:03:26] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:03:34,043 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:03:34] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:03:38,759 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:03:38,759 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:03:38,759 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:03:38,778 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:03:38,779 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:03:38,971 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:03:38,971 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:03:38,971 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:03:38,990 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:03:38,990 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:03:41,432 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:03:41] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:03:42,773 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:03:42] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:09:22,381 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:09:22,382 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:09:22,382 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:09:22,401 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:09:22,402 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:09:22,588 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:09:22,588 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:09:22,588 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:09:22,604 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:09:22,605 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:09:27,113 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:09:27] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:09:27,321 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:09:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2021-02-20 09:10:32,734 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:10:32] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:10:38,795 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:10:38] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:10:56,151 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:10:56] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:11:03,412 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:11:03] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:11:09,384 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:11:09] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:11:17,889 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:11:17] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:11:29,177 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:11:29] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:12:11,281 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:12:11] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:16:36,370 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[35m[1mGET / HTTP/1.1[0m" 500 -
2021-02-20 09:16:36,417 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:16:36,420 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:16:36,421 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:16:36,697 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:16:36,725 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:16:36] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:19:49,585 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/app.py', reloading
2021-02-20 09:19:49,632 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:19:49,827 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:19:49,828 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:19:49,828 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:19:49,845 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:19:49,846 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:21:47,618 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/utils/database_managment.py', reloading
2021-02-20 09:21:47,663 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:21:47,856 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:21:47,856 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:21:47,856 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:21:47,875 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:21:47,876 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:22:12,032 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/utils/database_managment.py', reloading
2021-02-20 09:22:12,078 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:26:08,619 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:26:08,619 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:26:08,619 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:26:08,639 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:26:08,640 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:26:08,827 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:26:08,828 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:26:08,828 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:26:08,847 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:26:08,847 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:26:11,808 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
2021-02-20 09:26:11,858 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:11] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:26:11,864 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:11] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:11,867 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:11] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:12,142 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:12] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:26:12,176 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:12] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:26:24,949 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/app.py', reloading
2021-02-20 09:26:24,995 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:26:25,191 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:26:25,192 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:26:25,192 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:26:25,211 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:26:25,212 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:26:28,599 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
2021-02-20 09:26:28,636 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:26:28,643 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:28,646 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:28,786 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:26:28,811 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:28] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:26:35,292 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:26:35,292 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:26:35,292 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:26:35,313 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:26:35,314 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:26:35,501 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:26:35,501 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:26:35,501 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:26:35,521 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:26:35,521 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:26:36,452 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[35m[1mGET / HTTP/1.1[0m" 500 -
2021-02-20 09:26:36,485 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:26:36,490 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:36,492 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:26:36,626 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:26:36,652 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:26:36] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:27:37,316 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:37] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:27:40,538 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:27:40,583 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:27:40,586 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:27:40,586 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:27:40,704 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:27:40,728 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:27:40] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:28:17,159 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/utils/database_managment.py', reloading
2021-02-20 09:28:17,208 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:28:17,400 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:28:17,400 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:28:17,400 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:28:17,418 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:28:17,419 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:28:18,428 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/utils/database_managment.py', reloading
2021-02-20 09:28:18,470 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:28:18,670 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:28:18,670 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:28:18,670 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:28:18,690 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:28:18,691 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:28:24,179 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:28:24,179 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:28:24,179 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:28:24,201 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-20 09:28:24,202 INFO     [_internal.py:113]  * Restarting with stat
2021-02-20 09:28:24,387 DEBUG    [database_managment.py:21] 'Database' object referred to utils/database_file.db
2021-02-20 09:28:24,387 DEBUG    [database_managment.py:40] Checking if utils/database_file.db exists
2021-02-20 09:28:24,388 DEBUG    [database_managment.py:42] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-20 09:28:24,405 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-20 09:28:24,406 INFO     [_internal.py:113]  * Debugger PIN: 163-567-502
2021-02-20 09:28:27,406 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:28:27,443 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:28:27,447 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:28:27,449 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:28:27,589 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:28:27,618 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:27] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:28:41,383 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:28:41,421 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:28:41,422 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:28:41,431 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:28:41,552 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:28:41,580 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:28:41] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:29:00,858 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:00] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:29:00,904 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:00] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:29:00,911 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:00] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:29:00,913 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:00] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:29:01,080 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:01] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:29:01,121 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:01] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:29:24,215 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:29:24,253 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:29:24,258 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:29:24,264 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:29:24,387 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:29:24,414 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:29:24] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:30:55,383 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[35m[1mGET /display_totals HTTP/1.1[0m" 500 -
2021-02-20 09:30:55,421 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-02-20 09:30:55,426 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-02-20 09:30:55,426 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-02-20 09:30:55,562 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:30:55,585 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:30:55] "[37mGET /display_totals?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-02-20 09:31:08,470 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:31:08] "[37mGET /display_totals HTTP/1.1[0m" 200 -
2021-02-20 09:31:14,741 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:31:14] "[37mGET / HTTP/1.1[0m" 200 -
2021-02-20 09:33:21,439 INFO     [_internal.py:113] 127.0.0.1 - - [20/Feb/2021 09:33:21] "[37mGET /display_totals HTTP/1.1[0m" 200 -
